from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pico_window(object):
    def setupUi(self, pico_window):
        pico_window.setObjectName("pico_window")
        pico_window.resize(390, 300)
        self.centralwidget = QtWidgets.QWidget(pico_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 250, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 170, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 76, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.qty_pico = QtWidgets.QSpinBox(self.centralwidget)
        self.qty_pico.setGeometry(QtCore.QRect(160, 160, 42, 22))
        self.qty_pico.setObjectName("qty_pico")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.saveBtn_pico3G = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn_pico3G.setGeometry(QtCore.QRect(20, 230, 91, 31))
        self.saveBtn_pico3G.setObjectName("saveBtn_pico3G")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(280, 230, 91, 31))
        self.exitBtn.setObjectName("exitBtn")
        self.bckBtn_pico3G = QtWidgets.QPushButton(self.centralwidget)
        self.bckBtn_pico3G.setGeometry(QtCore.QRect(150, 230, 91, 31))
        self.bckBtn_pico3G.setObjectName("bckBtn_pico3G")
        self.sitename_Pico = QtWidgets.QLineEdit(self.centralwidget)
        self.sitename_Pico.setGeometry(QtCore.QRect(90, 80, 200, 20))
        self.sitename_Pico.setObjectName("sitename_Pico")
        self.woID_Pico = QtWidgets.QLineEdit(self.centralwidget)
        self.woID_Pico.setGeometry(QtCore.QRect(90, 110, 200, 20))
        self.woID_Pico.setObjectName("woID_Pico")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tech_pico_unit = QtWidgets.QComboBox(self.centralwidget)
        self.tech_pico_unit.setGeometry(QtCore.QRect(310, 160, 69, 22))
        self.tech_pico_unit.setObjectName("tech_pico_unit")
        self.tech_pico_unit.addItem("")
        self.tech_pico_unit.addItem("")
        self.tech_pico_unit.addItem("")
        pico_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(pico_window)
        self.statusbar.setObjectName("statusbar")
        pico_window.setStatusBar(self.statusbar)

        self.retranslateUi(pico_window)
        QtCore.QMetaObject.connectSlotsByName(pico_window)

    def retranslateUi(self, pico_window):
        _translate = QtCore.QCoreApplication.translate
        pico_window.setWindowTitle(_translate("pico_window", "Pico DWO"))
        self.label.setText(_translate("pico_window", "New PICO site DWO"))
        self.label_2.setText(_translate("pico_window", "Site Name"))
        self.label_4.setText(_translate("pico_window", "Number of PICO units"))
        self.label_5.setText(_translate("pico_window", "WO ID"))
        self.saveBtn_pico3G.setText(_translate("pico_window", "Save"))
        self.exitBtn.setText(_translate("pico_window", "Exit"))
        self.bckBtn_pico3G.setText(_translate("pico_window", "Back"))
        self.label_6.setText(_translate("pico_window", "Technology"))
        self.tech_pico_unit.setItemText(0, _translate("pico_window", "3G Unit"))
        self.tech_pico_unit.setItemText(1, _translate("pico_window", "4G Unit"))
        self.tech_pico_unit.setItemText(2, _translate("pico_window", "3G+4G Unit"))

