from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SRANSiteDWO(object):
    def setupUi(self, SRANSiteDWO):
        SRANSiteDWO.setObjectName("SRANSiteDWO")
        SRANSiteDWO.resize(671, 567)
        self.centralwidget = QtWidgets.QWidget(SRANSiteDWO)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_GSM = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_GSM.setGeometry(QtCore.QRect(320, 55, 40, 20))
        self.checkBox_GSM.setObjectName("checkBox_GSM")
        self.checkBox_L2100 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_L2100.setGeometry(QtCore.QRect(610, 65, 50, 20))
        self.checkBox_L2100.setObjectName("checkBox_L2100")
        self.checkBox_L900 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_L900.setGeometry(QtCore.QRect(550, 55, 50, 20))
        self.checkBox_L900.setObjectName("checkBox_L900")
        self.checkBox_L1800 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_L1800.setGeometry(QtCore.QRect(550, 75, 50, 20))
        self.checkBox_L1800.setObjectName("checkBox_L1800")
        self.checkBox_U2100 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_U2100.setGeometry(QtCore.QRect(430, 75, 50, 20))
        self.checkBox_U2100.setObjectName("checkBox_U2100")
        self.checkBox_U900 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_U900.setGeometry(QtCore.QRect(430, 55, 50, 20))
        self.checkBox_U900.setObjectName("checkBox_U900")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 55, 51, 41))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 55, 51, 41))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(490, 55, 51, 41))
        self.label_10.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.checkBox_DCS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_DCS.setGeometry(QtCore.QRect(320, 75, 40, 20))
        self.checkBox_DCS.setObjectName("checkBox_DCS")
        self.saveBtn_SRAN = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn_SRAN.setGeometry(QtCore.QRect(214, 510, 90, 31))
        self.saveBtn_SRAN.setObjectName("saveBtn_SRAN")
        self.exitBtn_SRAN = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn_SRAN.setGeometry(QtCore.QRect(518, 510, 90, 31))
        self.exitBtn_SRAN.setObjectName("exitBtn_SRAN")
        self.bckBtn_SRAN = QtWidgets.QPushButton(self.centralwidget)
        self.bckBtn_SRAN.setGeometry(QtCore.QRect(366, 510, 90, 31))
        self.bckBtn_SRAN.setObjectName("bckBtn_SRAN")
        self.extract_consolidated_SRAN = QtWidgets.QPushButton(self.centralwidget)
        self.extract_consolidated_SRAN.setGeometry(QtCore.QRect(40, 510, 120, 31))
        self.extract_consolidated_SRAN.setObjectName("extract_consolidated_SRAN")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 670, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.siteName_SRAN = QtWidgets.QLineEdit(self.centralwidget)
        self.siteName_SRAN.setGeometry(QtCore.QRect(80, 50, 170, 20))
        self.siteName_SRAN.setAlignment(QtCore.Qt.AlignCenter)
        self.siteName_SRAN.setObjectName("siteName_SRAN")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(5, 120, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.sectors_SRAN = QtWidgets.QSpinBox(self.centralwidget)
        self.sectors_SRAN.setGeometry(QtCore.QRect(80, 120, 42, 20))
        self.sectors_SRAN.setMinimum(1)
        self.sectors_SRAN.setMaximum(6)
        self.sectors_SRAN.setProperty("value", 3)
        self.sectors_SRAN.setObjectName("sectors_SRAN")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 120, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.RRHtype_SRAN = QtWidgets.QComboBox(self.centralwidget)
        self.RRHtype_SRAN.setGeometry(QtCore.QRect(210, 120, 80, 20))
        self.RRHtype_SRAN.setObjectName("RRHtype_SRAN")
        self.RRHtype_SRAN.addItem("")
        self.RRHtype_SRAN.addItem("")
        self.RRHtype_SRAN.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 120, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.jumperType_SRAN = QtWidgets.QComboBox(self.centralwidget)
        self.jumperType_SRAN.setGeometry(QtCore.QRect(360, 120, 175, 20))
        self.jumperType_SRAN.setObjectName("jumperType_SRAN")
        self.jumperType_SRAN.addItem("")
        self.jumperType_SRAN.addItem("")
        self.jumperType_SRAN.addItem("")
        self.jumperType_SRAN.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(5, 160, 201, 25))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.trx_S1 = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S1.setGeometry(QtCore.QRect(5, 220, 45, 20))
        self.trx_S1.setObjectName("trx_S1")
        self.trx_S2 = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S2.setGeometry(QtCore.QRect(60, 220, 45, 20))
        self.trx_S2.setObjectName("trx_S2")
        self.trx_S3 = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S3.setGeometry(QtCore.QRect(110, 220, 45, 20))
        self.trx_S3.setObjectName("trx_S3")
        self.trx_S4 = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S4.setGeometry(QtCore.QRect(160, 220, 45, 20))
        self.trx_S4.setObjectName("trx_S4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(5, 195, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 195, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(110, 195, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 195, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.trxS1_Pwr = QtWidgets.QComboBox(self.centralwidget)
        self.trxS1_Pwr.setGeometry(QtCore.QRect(5, 240, 45, 20))
        self.trxS1_Pwr.setObjectName("trxS1_Pwr")
        self.trxS1_Pwr.addItem("")
        self.trxS1_Pwr.addItem("")
        self.trxS1_Pwr.addItem("")
        self.trxS1_Pwr.addItem("")
        self.trxS1_Pwr.addItem("")
        self.trxS2_Pwr = QtWidgets.QComboBox(self.centralwidget)
        self.trxS2_Pwr.setGeometry(QtCore.QRect(60, 240, 45, 20))
        self.trxS2_Pwr.setObjectName("trxS2_Pwr")
        self.trxS2_Pwr.addItem("")
        self.trxS2_Pwr.addItem("")
        self.trxS2_Pwr.addItem("")
        self.trxS2_Pwr.addItem("")
        self.trxS2_Pwr.addItem("")
        self.trxS3_Pwr = QtWidgets.QComboBox(self.centralwidget)
        self.trxS3_Pwr.setGeometry(QtCore.QRect(110, 240, 45, 20))
        self.trxS3_Pwr.setObjectName("trxS3_Pwr")
        self.trxS3_Pwr.addItem("")
        self.trxS3_Pwr.addItem("")
        self.trxS3_Pwr.addItem("")
        self.trxS3_Pwr.addItem("")
        self.trxS3_Pwr.addItem("")
        self.trxS4_Pwr = QtWidgets.QComboBox(self.centralwidget)
        self.trxS4_Pwr.setGeometry(QtCore.QRect(160, 240, 45, 20))
        self.trxS4_Pwr.setObjectName("trxS4_Pwr")
        self.trxS4_Pwr.addItem("")
        self.trxS4_Pwr.addItem("")
        self.trxS4_Pwr.addItem("")
        self.trxS4_Pwr.addItem("")
        self.trxS4_Pwr.addItem("")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(220, 160, 191, 25))
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(220, 190, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(260, 190, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(300, 190, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.CE_2100 = QtWidgets.QLineEdit(self.centralwidget)
        self.CE_2100.setGeometry(QtCore.QRect(220, 219, 40, 20))
        self.CE_2100.setAlignment(QtCore.Qt.AlignCenter)
        self.CE_2100.setObjectName("CE_2100")
        self.HSDPA_2100 = QtWidgets.QLineEdit(self.centralwidget)
        self.HSDPA_2100.setGeometry(QtCore.QRect(300, 219, 40, 20))
        self.HSDPA_2100.setAlignment(QtCore.Qt.AlignCenter)
        self.HSDPA_2100.setObjectName("HSDPA_2100")
        self.HSUPA_2100 = QtWidgets.QLineEdit(self.centralwidget)
        self.HSUPA_2100.setGeometry(QtCore.QRect(260, 219, 40, 20))
        self.HSUPA_2100.setAlignment(QtCore.Qt.AlignCenter)
        self.HSUPA_2100.setObjectName("HSUPA_2100")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(360, 190, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.pwr_U2100 = QtWidgets.QComboBox(self.centralwidget)
        self.pwr_U2100.setGeometry(QtCore.QRect(360, 219, 50, 20))
        self.pwr_U2100.setObjectName("pwr_U2100")
        self.pwr_U2100.addItem("")
        self.pwr_U2100.addItem("")
        self.pwr_U2100.addItem("")
        self.pwr_U2100.addItem("")
        self.pwr_U2100.addItem("")
        self.pwr_U2100.addItem("")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(430, 160, 241, 25))
        self.label_33.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(580, 250, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(440, 270, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(480, 270, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(550, 210, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(510, 210, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(440, 250, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(620, 270, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_40.setFrameShape(QtWidgets.QFrame.Box)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(580, 270, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_41.setFrameShape(QtWidgets.QFrame.Box)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(510, 190, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_42.setFrameShape(QtWidgets.QFrame.Box)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.L900_BW = QtWidgets.QComboBox(self.centralwidget)
        self.L900_BW.setGeometry(QtCore.QRect(440, 290, 40, 20))
        self.L900_BW.setObjectName("L900_BW")
        self.L900_BW.addItem("")
        self.L900_BW.addItem("")
        self.L900_BW.addItem("")
        self.L900_BW.addItem("")
        self.L900_BW.addItem("")
        self.L1800_BW = QtWidgets.QComboBox(self.centralwidget)
        self.L1800_BW.setGeometry(QtCore.QRect(510, 230, 40, 20))
        self.L1800_BW.setObjectName("L1800_BW")
        self.L1800_BW.addItem("")
        self.L1800_BW.addItem("")
        self.L1800_BW.addItem("")
        self.L1800_BW.addItem("")
        self.L1800_BW.addItem("")
        self.L2100_BW = QtWidgets.QComboBox(self.centralwidget)
        self.L2100_BW.setGeometry(QtCore.QRect(580, 290, 40, 20))
        self.L2100_BW.setObjectName("L2100_BW")
        self.L2100_BW.addItem("")
        self.L2100_BW.addItem("")
        self.L2100_BW.addItem("")
        self.L2100_BW.addItem("")
        self.L2100_BW.addItem("")
        self.L900_pwr = QtWidgets.QComboBox(self.centralwidget)
        self.L900_pwr.setGeometry(QtCore.QRect(480, 290, 40, 20))
        self.L900_pwr.setObjectName("L900_pwr")
        self.L900_pwr.addItem("")
        self.L900_pwr.addItem("")
        self.L900_pwr.addItem("")
        self.L900_pwr.addItem("")
        self.L1800_pwr = QtWidgets.QComboBox(self.centralwidget)
        self.L1800_pwr.setGeometry(QtCore.QRect(550, 230, 40, 20))
        self.L1800_pwr.setObjectName("L1800_pwr")
        self.L1800_pwr.addItem("")
        self.L1800_pwr.addItem("")
        self.L1800_pwr.addItem("")
        self.L1800_pwr.addItem("")
        self.L2100_pwr = QtWidgets.QComboBox(self.centralwidget)
        self.L2100_pwr.setGeometry(QtCore.QRect(620, 290, 40, 20))
        self.L2100_pwr.setObjectName("L2100_pwr")
        self.L2100_pwr.addItem("")
        self.L2100_pwr.addItem("")
        self.L2100_pwr.addItem("")
        self.L2100_pwr.addItem("")
        self.L1800_MIMO = QtWidgets.QComboBox(self.centralwidget)
        self.L1800_MIMO.setGeometry(QtCore.QRect(620, 120, 50, 20))
        self.L1800_MIMO.setObjectName("L1800_MIMO")
        self.L1800_MIMO.addItem("")
        self.L1800_MIMO.addItem("")
        self.B900_RFtype = QtWidgets.QComboBox(self.centralwidget)
        self.B900_RFtype.setGeometry(QtCore.QRect(120, 270, 51, 20))
        self.B900_RFtype.setObjectName("B900_RFtype")
        self.B900_RFtype.addItem("")
        self.B900_RFtype.addItem("")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(20, 270, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.B2100_RFtype = QtWidgets.QComboBox(self.centralwidget)
        self.B2100_RFtype.setGeometry(QtCore.QRect(340, 290, 51, 20))
        self.B2100_RFtype.setObjectName("B2100_RFtype")
        self.B2100_RFtype.addItem("")
        self.B2100_RFtype.addItem("")
        self.B2100_RFtype.addItem("")
        self.B2100_RFtype.addItem("")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(230, 290, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.B1800_RFtype = QtWidgets.QComboBox(self.centralwidget)
        self.B1800_RFtype.setGeometry(QtCore.QRect(570, 330, 51, 20))
        self.B1800_RFtype.setObjectName("B1800_RFtype")
        self.B1800_RFtype.addItem("")
        self.B1800_RFtype.addItem("")
        self.B1800_RFtype.addItem("")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(470, 330, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 80, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.woID_SRAN = QtWidgets.QLineEdit(self.centralwidget)
        self.woID_SRAN.setGeometry(QtCore.QRect(80, 80, 170, 20))
        self.woID_SRAN.setAlignment(QtCore.Qt.AlignCenter)
        self.woID_SRAN.setObjectName("woID_SRAN")
        self.executeBtn_SRAN = QtWidgets.QPushButton(self.centralwidget)
        self.executeBtn_SRAN.setGeometry(QtCore.QRect(10, 395, 80, 75))
        self.executeBtn_SRAN.setObjectName("executeBtn_SRAN")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(200, 150, 20, 231))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(410, 150, 20, 231))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(560, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 140, 671, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 370, 671, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 100, 671, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(120, 110, 20, 41))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(290, 110, 20, 41))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(540, 110, 20, 41))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_tgt_SM = QtWidgets.QLabel(self.centralwidget)
        self.label_tgt_SM.setGeometry(QtCore.QRect(100, 430, 175, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_tgt_SM.setFont(font)
        self.label_tgt_SM.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_tgt_SM.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tgt_SM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tgt_SM.setObjectName("label_tgt_SM")
        self.label_tgt_900RF = QtWidgets.QLabel(self.centralwidget)
        self.label_tgt_900RF.setGeometry(QtCore.QRect(285, 430, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_tgt_900RF.setFont(font)
        self.label_tgt_900RF.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_tgt_900RF.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tgt_900RF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tgt_900RF.setObjectName("label_tgt_900RF")
        self.label_needed_HW = QtWidgets.QLabel(self.centralwidget)
        self.label_needed_HW.setGeometry(QtCore.QRect(100, 394, 555, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_needed_HW.setFont(font)
        self.label_needed_HW.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);")
        self.label_needed_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.label_needed_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_needed_HW.setObjectName("label_needed_HW")
        self.trgt_2100_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_2100_text.setGeometry(QtCore.QRect(405, 450, 60, 20))
        self.trgt_2100_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_2100_text.setObjectName("trgt_2100_text")
        self.label_tgt_1800RF = QtWidgets.QLabel(self.centralwidget)
        self.label_tgt_1800RF.setGeometry(QtCore.QRect(475, 430, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_tgt_1800RF.setFont(font)
        self.label_tgt_1800RF.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_tgt_1800RF.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tgt_1800RF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tgt_1800RF.setObjectName("label_tgt_1800RF")
        self.trgt_1800_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_1800_text.setGeometry(QtCore.QRect(500, 450, 60, 20))
        self.trgt_1800_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_1800_text.setObjectName("trgt_1800_text")
        self.trgt_FSMF_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_FSMF_text.setGeometry(QtCore.QRect(125, 450, 50, 20))
        self.trgt_FSMF_text.setInputMask("")
        self.trgt_FSMF_text.setText("")
        self.trgt_FSMF_text.setMaxLength(32767)
        self.trgt_FSMF_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_FSMF_text.setObjectName("trgt_FSMF_text")
        self.label_tgt_2100RF = QtWidgets.QLabel(self.centralwidget)
        self.label_tgt_2100RF.setGeometry(QtCore.QRect(380, 430, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_tgt_2100RF.setFont(font)
        self.label_tgt_2100RF.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_tgt_2100RF.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tgt_2100RF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tgt_2100RF.setObjectName("label_tgt_2100RF")
        self.trgt_900_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_900_text.setGeometry(QtCore.QRect(310, 450, 60, 20))
        self.trgt_900_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_900_text.setObjectName("trgt_900_text")
        self.trgt_FSMF_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_FSMF_qty.setGeometry(QtCore.QRect(100, 450, 25, 20))
        self.trgt_FSMF_qty.setInputMask("")
        self.trgt_FSMF_qty.setText("")
        self.trgt_FSMF_qty.setMaxLength(32767)
        self.trgt_FSMF_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_FSMF_qty.setObjectName("trgt_FSMF_qty")
        self.trgt_FBBC_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_FBBC_qty.setGeometry(QtCore.QRect(200, 450, 25, 20))
        self.trgt_FBBC_qty.setInputMask("")
        self.trgt_FBBC_qty.setText("")
        self.trgt_FBBC_qty.setMaxLength(32767)
        self.trgt_FBBC_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_FBBC_qty.setObjectName("trgt_FBBC_qty")
        self.trgt_FBBC_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_FBBC_text.setGeometry(QtCore.QRect(225, 450, 50, 20))
        self.trgt_FBBC_text.setInputMask("")
        self.trgt_FBBC_text.setText("")
        self.trgt_FBBC_text.setMaxLength(32767)
        self.trgt_FBBC_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_FBBC_text.setObjectName("trgt_FBBC_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 450, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.trgt_900RF_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_900RF_qty.setGeometry(QtCore.QRect(285, 450, 25, 20))
        self.trgt_900RF_qty.setInputMask("")
        self.trgt_900RF_qty.setText("")
        self.trgt_900RF_qty.setMaxLength(32767)
        self.trgt_900RF_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_900RF_qty.setObjectName("trgt_900RF_qty")
        self.trgt_2100RF_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_2100RF_qty.setGeometry(QtCore.QRect(380, 450, 25, 20))
        self.trgt_2100RF_qty.setInputMask("")
        self.trgt_2100RF_qty.setText("")
        self.trgt_2100RF_qty.setMaxLength(32767)
        self.trgt_2100RF_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_2100RF_qty.setObjectName("trgt_2100RF_qty")
        self.trgt_1800RF_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_1800RF_qty.setGeometry(QtCore.QRect(475, 450, 25, 20))
        self.trgt_1800RF_qty.setInputMask("")
        self.trgt_1800RF_qty.setText("")
        self.trgt_1800RF_qty.setMaxLength(32767)
        self.trgt_1800RF_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_1800RF_qty.setObjectName("trgt_1800RF_qty")
        self.HSDPA_900 = QtWidgets.QLineEdit(self.centralwidget)
        self.HSDPA_900.setGeometry(QtCore.QRect(300, 240, 40, 20))
        self.HSDPA_900.setAlignment(QtCore.Qt.AlignCenter)
        self.HSDPA_900.setObjectName("HSDPA_900")
        self.HSUPA_900 = QtWidgets.QLineEdit(self.centralwidget)
        self.HSUPA_900.setGeometry(QtCore.QRect(260, 240, 40, 20))
        self.HSUPA_900.setAlignment(QtCore.Qt.AlignCenter)
        self.HSUPA_900.setObjectName("HSUPA_900")
        self.pwr_U900 = QtWidgets.QComboBox(self.centralwidget)
        self.pwr_U900.setGeometry(QtCore.QRect(360, 240, 50, 20))
        self.pwr_U900.setObjectName("pwr_U900")
        self.pwr_U900.addItem("")
        self.pwr_U900.addItem("")
        self.pwr_U900.addItem("")
        self.pwr_U900.addItem("")
        self.pwr_U900.addItem("")
        self.pwr_U900.addItem("")
        self.CE_900 = QtWidgets.QLineEdit(self.centralwidget)
        self.CE_900.setGeometry(QtCore.QRect(220, 240, 40, 20))
        self.CE_900.setAlignment(QtCore.Qt.AlignCenter)
        self.CE_900.setObjectName("CE_900")
        self.u2100_carriers = QtWidgets.QSpinBox(self.centralwidget)
        self.u2100_carriers.setGeometry(QtCore.QRect(340, 330, 51, 20))
        self.u2100_carriers.setObjectName("u2100_carriers")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(230, 330, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.dcs_RFtype = QtWidgets.QComboBox(self.centralwidget)
        self.dcs_RFtype.setGeometry(QtCore.QRect(60, 350, 141, 20))
        self.dcs_RFtype.setObjectName("dcs_RFtype")
        self.dcs_RFtype.addItem("")
        self.dcs_RFtype.addItem("")
        self.dcs_RFtype.addItem("")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(10, 350, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.trx_S3_dcs = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S3_dcs.setGeometry(QtCore.QRect(110, 320, 45, 20))
        self.trx_S3_dcs.setObjectName("trx_S3_dcs")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 300, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(5, 300, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.trx_S2_dcs = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S2_dcs.setGeometry(QtCore.QRect(60, 320, 45, 20))
        self.trx_S2_dcs.setObjectName("trx_S2_dcs")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(110, 300, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(160, 300, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.trx_S4_dcs = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S4_dcs.setGeometry(QtCore.QRect(160, 320, 45, 20))
        self.trx_S4_dcs.setObjectName("trx_S4_dcs")
        self.trx_S1_dcs = QtWidgets.QSpinBox(self.centralwidget)
        self.trx_S1_dcs.setGeometry(QtCore.QRect(5, 320, 45, 20))
        self.trx_S1_dcs.setObjectName("trx_S1_dcs")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(0, 480, 671, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(560, 450, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.trgt_RF_qty_DCS = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_RF_qty_DCS.setGeometry(QtCore.QRect(580, 450, 25, 20))
        self.trgt_RF_qty_DCS.setInputMask("")
        self.trgt_RF_qty_DCS.setText("")
        self.trgt_RF_qty_DCS.setMaxLength(32767)
        self.trgt_RF_qty_DCS.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_RF_qty_DCS.setObjectName("trgt_RF_qty_DCS")
        self.trgt_DCS_text = QtWidgets.QLineEdit(self.centralwidget)
        self.trgt_DCS_text.setGeometry(QtCore.QRect(605, 450, 50, 20))
        self.trgt_DCS_text.setInputMask("")
        self.trgt_DCS_text.setText("")
        self.trgt_DCS_text.setMaxLength(32767)
        self.trgt_DCS_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trgt_DCS_text.setObjectName("trgt_DCS_text")
        self.label_tgt_1800RF_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_tgt_1800RF_2.setGeometry(QtCore.QRect(580, 430, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_tgt_1800RF_2.setFont(font)
        self.label_tgt_1800RF_2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_tgt_1800RF_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_tgt_1800RF_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tgt_1800RF_2.setObjectName("label_tgt_1800RF_2")
        SRANSiteDWO.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SRANSiteDWO)
        self.statusbar.setObjectName("statusbar")
        SRANSiteDWO.setStatusBar(self.statusbar)

        self.retranslateUi(SRANSiteDWO)
        QtCore.QMetaObject.connectSlotsByName(SRANSiteDWO)

    def retranslateUi(self, SRANSiteDWO):
        _translate = QtCore.QCoreApplication.translate
        SRANSiteDWO.setWindowTitle(_translate("SRANSiteDWO", "SRAN Site DWO"))
        self.checkBox_GSM.setText(_translate("SRANSiteDWO", "GSM"))
        self.checkBox_L2100.setText(_translate("SRANSiteDWO", "L2100"))
        self.checkBox_L900.setText(_translate("SRANSiteDWO", "L900"))
        self.checkBox_L1800.setText(_translate("SRANSiteDWO", "L1800"))
        self.checkBox_U2100.setText(_translate("SRANSiteDWO", "U2100"))
        self.checkBox_U900.setText(_translate("SRANSiteDWO", "U900"))
        self.label_8.setText(_translate("SRANSiteDWO", "2G"))
        self.label_9.setText(_translate("SRANSiteDWO", "UMTS"))
        self.label_10.setText(_translate("SRANSiteDWO", "LTE"))
        self.checkBox_DCS.setText(_translate("SRANSiteDWO", "DCS"))
        self.saveBtn_SRAN.setText(_translate("SRANSiteDWO", "Save MO"))
        self.exitBtn_SRAN.setText(_translate("SRANSiteDWO", "Exit"))
        self.bckBtn_SRAN.setText(_translate("SRANSiteDWO", "Back"))
        self.extract_consolidated_SRAN.setText(_translate("SRANSiteDWO", "Extract Consolidated"))
        self.label.setText(_translate("SRANSiteDWO", "New SRAN site DWO/Consolidated Sheet"))
        self.label_13.setText(_translate("SRANSiteDWO", "Site Name"))
        self.label_4.setText(_translate("SRANSiteDWO", "# of Sectors"))
        self.label_7.setText(_translate("SRANSiteDWO", "Jumper"))
        self.RRHtype_SRAN.setCurrentText(_translate("SRANSiteDWO", "Feederless"))
        self.RRHtype_SRAN.setItemText(0, _translate("SRANSiteDWO", "Feederless"))
        self.RRHtype_SRAN.setItemText(1, _translate("SRANSiteDWO", "Feeder"))
        self.RRHtype_SRAN.setItemText(2, _translate("SRANSiteDWO", "Roof Top"))
        self.label_6.setText(_translate("SRANSiteDWO", "RRH Type"))
        self.jumperType_SRAN.setCurrentText(_translate("SRANSiteDWO", "Jumpers_4.3-10 To 4.3-10_5M"))
        self.jumperType_SRAN.setItemText(0, _translate("SRANSiteDWO", "Jumpers_4.3-10 To 4.3-10_5M"))
        self.jumperType_SRAN.setItemText(1, _translate("SRANSiteDWO", "Jumpers_4.3-10 To 4.3-10_9M"))
        self.jumperType_SRAN.setItemText(2, _translate("SRANSiteDWO", "Jumpers_4.3-10 To 7/16_5M"))
        self.jumperType_SRAN.setItemText(3, _translate("SRANSiteDWO", "Jumpers_4.3-10 To 7/16_9M"))
        self.label_11.setText(_translate("SRANSiteDWO", "2G Configuration"))
        self.label_3.setText(_translate("SRANSiteDWO", "GSM S1"))
        self.label_5.setText(_translate("SRANSiteDWO", "GSM S2"))
        self.label_14.setText(_translate("SRANSiteDWO", "GSM S3"))
        self.label_15.setText(_translate("SRANSiteDWO", "GSM S4"))
        self.trxS1_Pwr.setCurrentText(_translate("SRANSiteDWO", "5W"))
        self.trxS1_Pwr.setItemText(0, _translate("SRANSiteDWO", "5W"))
        self.trxS1_Pwr.setItemText(1, _translate("SRANSiteDWO", "10W"))
        self.trxS1_Pwr.setItemText(2, _translate("SRANSiteDWO", "12W"))
        self.trxS1_Pwr.setItemText(3, _translate("SRANSiteDWO", "15W"))
        self.trxS1_Pwr.setItemText(4, _translate("SRANSiteDWO", "20W"))
        self.trxS2_Pwr.setCurrentText(_translate("SRANSiteDWO", "5W"))
        self.trxS2_Pwr.setItemText(0, _translate("SRANSiteDWO", "5W"))
        self.trxS2_Pwr.setItemText(1, _translate("SRANSiteDWO", "10W"))
        self.trxS2_Pwr.setItemText(2, _translate("SRANSiteDWO", "12W"))
        self.trxS2_Pwr.setItemText(3, _translate("SRANSiteDWO", "15W"))
        self.trxS2_Pwr.setItemText(4, _translate("SRANSiteDWO", "20W"))
        self.trxS3_Pwr.setCurrentText(_translate("SRANSiteDWO", "5W"))
        self.trxS3_Pwr.setItemText(0, _translate("SRANSiteDWO", "5W"))
        self.trxS3_Pwr.setItemText(1, _translate("SRANSiteDWO", "10W"))
        self.trxS3_Pwr.setItemText(2, _translate("SRANSiteDWO", "12W"))
        self.trxS3_Pwr.setItemText(3, _translate("SRANSiteDWO", "15W"))
        self.trxS3_Pwr.setItemText(4, _translate("SRANSiteDWO", "20W"))
        self.trxS4_Pwr.setCurrentText(_translate("SRANSiteDWO", "5W"))
        self.trxS4_Pwr.setItemText(0, _translate("SRANSiteDWO", "5W"))
        self.trxS4_Pwr.setItemText(1, _translate("SRANSiteDWO", "10W"))
        self.trxS4_Pwr.setItemText(2, _translate("SRANSiteDWO", "12W"))
        self.trxS4_Pwr.setItemText(3, _translate("SRANSiteDWO", "15W"))
        self.trxS4_Pwr.setItemText(4, _translate("SRANSiteDWO", "20W"))
        self.label_24.setText(_translate("SRANSiteDWO", "3G/U900 Configuration"))
        self.label_25.setText(_translate("SRANSiteDWO", "CE"))
        self.label_26.setText(_translate("SRANSiteDWO", "HSUPA"))
        self.label_27.setText(_translate("SRANSiteDWO", "HSDPA"))
        self.label_28.setText(_translate("SRANSiteDWO", "Power"))
        self.pwr_U2100.setCurrentText(_translate("SRANSiteDWO", "20W"))
        self.pwr_U2100.setItemText(0, _translate("SRANSiteDWO", "20W"))
        self.pwr_U2100.setItemText(1, _translate("SRANSiteDWO", "30W"))
        self.pwr_U2100.setItemText(2, _translate("SRANSiteDWO", "40W"))
        self.pwr_U2100.setItemText(3, _translate("SRANSiteDWO", "53W"))
        self.pwr_U2100.setItemText(4, _translate("SRANSiteDWO", "60W"))
        self.pwr_U2100.setItemText(5, _translate("SRANSiteDWO", "80W"))
        self.label_33.setText(_translate("SRANSiteDWO", "LTE Configuration"))
        self.label_34.setText(_translate("SRANSiteDWO", "L2100"))
        self.label_35.setText(_translate("SRANSiteDWO", "BW"))
        self.label_36.setText(_translate("SRANSiteDWO", "Power"))
        self.label_37.setText(_translate("SRANSiteDWO", "Power"))
        self.label_38.setText(_translate("SRANSiteDWO", "BW"))
        self.label_39.setText(_translate("SRANSiteDWO", "L900"))
        self.label_40.setText(_translate("SRANSiteDWO", "Power"))
        self.label_41.setText(_translate("SRANSiteDWO", "BW"))
        self.label_42.setText(_translate("SRANSiteDWO", "L1800"))
        self.L900_BW.setCurrentText(_translate("SRANSiteDWO", "0"))
        self.L900_BW.setItemText(0, _translate("SRANSiteDWO", "0"))
        self.L900_BW.setItemText(1, _translate("SRANSiteDWO", "5"))
        self.L900_BW.setItemText(2, _translate("SRANSiteDWO", "10"))
        self.L900_BW.setItemText(3, _translate("SRANSiteDWO", "15"))
        self.L900_BW.setItemText(4, _translate("SRANSiteDWO", "20"))
        self.L1800_BW.setCurrentText(_translate("SRANSiteDWO", "0"))
        self.L1800_BW.setItemText(0, _translate("SRANSiteDWO", "0"))
        self.L1800_BW.setItemText(1, _translate("SRANSiteDWO", "5"))
        self.L1800_BW.setItemText(2, _translate("SRANSiteDWO", "10"))
        self.L1800_BW.setItemText(3, _translate("SRANSiteDWO", "15"))
        self.L1800_BW.setItemText(4, _translate("SRANSiteDWO", "20"))
        self.L2100_BW.setCurrentText(_translate("SRANSiteDWO", "0"))
        self.L2100_BW.setItemText(0, _translate("SRANSiteDWO", "0"))
        self.L2100_BW.setItemText(1, _translate("SRANSiteDWO", "5"))
        self.L2100_BW.setItemText(2, _translate("SRANSiteDWO", "10"))
        self.L2100_BW.setItemText(3, _translate("SRANSiteDWO", "15"))
        self.L2100_BW.setItemText(4, _translate("SRANSiteDWO", "20"))
        self.L900_pwr.setCurrentText(_translate("SRANSiteDWO", "20"))
        self.L900_pwr.setItemText(0, _translate("SRANSiteDWO", "20"))
        self.L900_pwr.setItemText(1, _translate("SRANSiteDWO", "40"))
        self.L900_pwr.setItemText(2, _translate("SRANSiteDWO", "60"))
        self.L900_pwr.setItemText(3, _translate("SRANSiteDWO", "80"))
        self.L1800_pwr.setCurrentText(_translate("SRANSiteDWO", "20"))
        self.L1800_pwr.setItemText(0, _translate("SRANSiteDWO", "20"))
        self.L1800_pwr.setItemText(1, _translate("SRANSiteDWO", "40"))
        self.L1800_pwr.setItemText(2, _translate("SRANSiteDWO", "60"))
        self.L1800_pwr.setItemText(3, _translate("SRANSiteDWO", "80"))
        self.L2100_pwr.setCurrentText(_translate("SRANSiteDWO", "20"))
        self.L2100_pwr.setItemText(0, _translate("SRANSiteDWO", "20"))
        self.L2100_pwr.setItemText(1, _translate("SRANSiteDWO", "40"))
        self.L2100_pwr.setItemText(2, _translate("SRANSiteDWO", "60"))
        self.L2100_pwr.setItemText(3, _translate("SRANSiteDWO", "80"))
        self.L1800_MIMO.setCurrentText(_translate("SRANSiteDWO", "2x2"))
        self.L1800_MIMO.setItemText(0, _translate("SRANSiteDWO", "2x2"))
        self.L1800_MIMO.setItemText(1, _translate("SRANSiteDWO", "4x4"))
        self.B900_RFtype.setCurrentText(_translate("SRANSiteDWO", "FXDB"))
        self.B900_RFtype.setItemText(0, _translate("SRANSiteDWO", "FXDB"))
        self.B900_RFtype.setItemText(1, _translate("SRANSiteDWO", "ARDA"))
        self.label_45.setText(_translate("SRANSiteDWO", "B900 RF Type"))
        self.B2100_RFtype.setCurrentText(_translate("SRANSiteDWO", "FRGT"))
        self.B2100_RFtype.setItemText(0, _translate("SRANSiteDWO", "FRGT"))
        self.B2100_RFtype.setItemText(1, _translate("SRANSiteDWO", "FRGX"))
        self.B2100_RFtype.setItemText(2, _translate("SRANSiteDWO", "ARGA"))
        self.B2100_RFtype.setItemText(3, _translate("SRANSiteDWO", "FRGU"))
        self.label_46.setText(_translate("SRANSiteDWO", "B2100 RF Type"))
        self.B1800_RFtype.setCurrentText(_translate("SRANSiteDWO", "AREA"))
        self.B1800_RFtype.setItemText(0, _translate("SRANSiteDWO", "AREA"))
        self.B1800_RFtype.setItemText(1, _translate("SRANSiteDWO", "FXEB"))
        self.B1800_RFtype.setItemText(2, _translate("SRANSiteDWO", "FXED"))
        self.label_47.setText(_translate("SRANSiteDWO", "B1800 RF Type"))
        self.label_17.setText(_translate("SRANSiteDWO", "WO ID"))
        self.executeBtn_SRAN.setText(_translate("SRANSiteDWO", "Execute"))
        self.label_18.setText(_translate("SRANSiteDWO", "LTE MIMO"))
        self.label_tgt_SM.setText(_translate("SRANSiteDWO", "SM"))
        self.label_tgt_900RF.setText(_translate("SRANSiteDWO", "900 RFs"))
        self.label_needed_HW.setText(_translate("SRANSiteDWO", "Needed Hardware"))
        self.label_tgt_1800RF.setText(_translate("SRANSiteDWO", "1800 RFs"))
        self.label_tgt_2100RF.setText(_translate("SRANSiteDWO", "2100 RFs"))
        self.label_2.setText(_translate("SRANSiteDWO", "+"))
        self.pwr_U900.setCurrentText(_translate("SRANSiteDWO", "20W"))
        self.pwr_U900.setItemText(0, _translate("SRANSiteDWO", "20W"))
        self.pwr_U900.setItemText(1, _translate("SRANSiteDWO", "30W"))
        self.pwr_U900.setItemText(2, _translate("SRANSiteDWO", "40W"))
        self.pwr_U900.setItemText(3, _translate("SRANSiteDWO", "53W"))
        self.pwr_U900.setItemText(4, _translate("SRANSiteDWO", "60W"))
        self.pwr_U900.setItemText(5, _translate("SRANSiteDWO", "80W"))
        self.label_48.setText(_translate("SRANSiteDWO", "3G # of carriers"))
        self.dcs_RFtype.setCurrentText(_translate("SRANSiteDWO", "FXEB"))
        self.dcs_RFtype.setItemText(0, _translate("SRANSiteDWO", "FXEB"))
        self.dcs_RFtype.setItemText(1, _translate("SRANSiteDWO", "FXEF"))
        self.dcs_RFtype.setItemText(2, _translate("SRANSiteDWO", "AREA Sharing"))
        self.label_49.setText(_translate("SRANSiteDWO", "DCS RF"))
        self.label_12.setText(_translate("SRANSiteDWO", "DCS S2"))
        self.label_16.setText(_translate("SRANSiteDWO", "DCS S1"))
        self.label_19.setText(_translate("SRANSiteDWO", "DCS S3"))
        self.label_20.setText(_translate("SRANSiteDWO", "DCS S4"))
        self.label_21.setText(_translate("SRANSiteDWO", "+"))
        self.label_tgt_1800RF_2.setText(_translate("SRANSiteDWO", "DCS RFs"))

