# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WelcomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeWindow(object):
    def setupUi(self, welcomeWindow):
        welcomeWindow.setObjectName("welcomeWindow")
        welcomeWindow.resize(501, 277)
        welcomeWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        welcomeWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(welcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(125, 23, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 400, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 85, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.upgradeWinBtn = QtWidgets.QPushButton(self.centralwidget)
        self.upgradeWinBtn.setGeometry(QtCore.QRect(230, 150, 100, 35))
        self.upgradeWinBtn.setObjectName("upgradeWinBtn")
        self.newsiteWinBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newsiteWinBtn.setGeometry(QtCore.QRect(350, 150, 100, 35))
        self.newsiteWinBtn.setObjectName("newsiteWinBtn")
        self.upload_stock_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_stock_btn.setGeometry(QtCore.QRect(70, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.upload_stock_btn.setFont(font)
        self.upload_stock_btn.setStyleSheet("")
        self.upload_stock_btn.setObjectName("upload_stock_btn")
        self.tddWinBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tddWinBtn.setGeometry(QtCore.QRect(290, 190, 100, 35))
        self.tddWinBtn.setObjectName("tddWinBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 130, 51, 61))
        self.label_3.setStyleSheet("image: url(:/images/upload_orange.png);")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        welcomeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(welcomeWindow)
        self.statusbar.setObjectName("statusbar")
        welcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(welcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(welcomeWindow)

    def retranslateUi(self, welcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        welcomeWindow.setWindowTitle(_translate("welcomeWindow", "DWO tool"))
        self.label.setText(_translate("welcomeWindow", "Welcome to DWO tool"))
        self.label_2.setText(_translate("welcomeWindow", "What do you want to do?"))
        self.upgradeWinBtn.setText(_translate("welcomeWindow", "Upgrade"))
        self.newsiteWinBtn.setText(_translate("welcomeWindow", "New Site"))
        self.upload_stock_btn.setText(_translate("welcomeWindow", "Upload Inventory"))
        self.tddWinBtn.setText(_translate("welcomeWindow", "TDD"))
import resources_rc
